alias ll='ls -la'
alias ls='ls -hF --color=tty'
alias subl='/c/Program\ Files/Sublime\ Text\ 3/sublime_text.exe'
alias chrome='/c/Program\ Files\ \(x86\)/Google/Chrome/Application/chrome.exe'
alias code='/c/Program\ Files\ \(x86\)/Microsoft\ VS\ Code/code.exe'
